# Generated by Django 5.2.8 on 2025-12-16 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpeditionLobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'En espera'), ('running', 'En progreso'), ('finished', 'Finalizada')], default='waiting', max_length=20)),
                ('phase', models.CharField(choices=[('waiting', 'Esperando jugadores'), ('vote_order_1', 'Votación: quién va primero'), ('vote_order_2', 'Votación: quién va segundo'), ('combat', 'Combate'), ('between', 'Entre pisos'), ('ended', 'Terminada')], default='waiting', max_length=30)),
                ('floor', models.PositiveIntegerField(default=1)),
                ('phase_deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expeditions_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpeditionChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='expeditions.expeditionlobby')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpeditionDailyEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('earned_coins', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedition_daily_earnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'day')},
            },
        ),
        migrations.CreateModel(
            name='ExpeditionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_hp', models.IntegerField(default=100)),
                ('base_attack', models.IntegerField(default=15)),
                ('base_defense', models.IntegerField(default=2)),
                ('max_hp', models.IntegerField(default=100)),
                ('current_hp', models.IntegerField(default=100)),
                ('attack', models.IntegerField(default=15)),
                ('defense', models.IntegerField(default=2)),
                ('is_alive', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='expeditions.expeditionlobby')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedition_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('lobby', 'user')},
            },
        ),
    ]
