# Generated by Django 5.2.8 on 2025-12-16 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expeditionlobby',
            name='current_fighter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expeditionlobby',
            name='enemy_attack',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expeditionlobby',
            name='enemy_defense',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expeditionlobby',
            name='enemy_hp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expeditionlobby',
            name='last_enemy_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='expeditionlobby',
            name='last_killer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expeditionlobby',
            name='optional_decision_type',
            field=models.CharField(choices=[('none', 'Sin decisión'), ('heal_50', 'Curar 50% HP a un jugador'), ('damage_30', 'Quitar 30% HP a un jugador (min 1)'), ('give_stats', 'Dar stats random (0..100) a un jugador'), ('take_stats', 'Quitar stats random (0..100) a un jugador')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='expeditionlobby',
            name='optional_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='expeditionlobby',
            name='order_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expeditionlobby',
            name='order_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ExpeditionRunResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('floor_reached', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lobby', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='run_result', to='expeditions.expeditionlobby')),
                ('user1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-floor_reached', '-created_at'],
                'indexes': [models.Index(fields=['day', 'floor_reached'], name='expeditions_day_39ff50_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExpeditionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='expeditions.expeditionlobby')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedition_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('lobby', 'phase', 'voter')},
            },
        ),
    ]
