# Generated by Django 5.2.8 on 2025-12-16 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0002_expeditionlobby_current_fighter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expeditionvote',
            options={},
        ),
        migrations.RemoveField(
            model_name='expeditionlobby',
            name='current_fighter',
        ),
        migrations.RemoveField(
            model_name='expeditionlobby',
            name='optional_decision_type',
        ),
        migrations.RemoveField(
            model_name='expeditionlobby',
            name='optional_payload',
        ),
        migrations.RemoveField(
            model_name='expeditionvote',
            name='target_user',
        ),
        migrations.AddField(
            model_name='expeditionlobby',
            name='decision_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expeditionlobby',
            name='decision_type',
            field=models.CharField(blank=True, choices=[('heal_50', 'Curar 50% HP a un jugador'), ('damage_30', 'Quitar 30% HP a un jugador'), ('give_stats', 'Dar stats aleatorias'), ('remove_stats', 'Quitar stats aleatorias')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='expeditionvote',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expeditionvote',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expeditionlobby',
            name='last_enemy_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expeditionlobby',
            name='phase',
            field=models.CharField(choices=[('waiting', 'Esperando jugadores'), ('vote_order_1', 'Votación: quién va primero'), ('vote_order_2', 'Votación: quién va segundo'), ('decision', 'Decisión (opcional)'), ('combat', 'Combate'), ('between', 'Entre pisos'), ('ended', 'Terminada')], default='waiting', max_length=30),
        ),
        migrations.AlterField(
            model_name='expeditionvote',
            name='phase',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='expeditionvote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ExpeditionRunResult',
        ),
    ]
