# Generated by Django 5.2.8 on 2025-12-16 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0003_alter_expeditionvote_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpeditionDailyPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('coins', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedition_daily_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('day', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ExpeditionRunResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('floor_reached', models.PositiveIntegerField(default=1)),
                ('member_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_results', to='expeditions.expeditionlobby')),
            ],
            options={
                'indexes': [models.Index(fields=['day', '-floor_reached', 'created_at'], name='expeditions_day_ddb29b_idx')],
            },
        ),
    ]
