# Generated by Django 5.2.8 on 2025-12-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0004_expeditiondailypayout_expeditionrunresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expeditionlobby',
            name='decision_type',
            field=models.CharField(blank=True, choices=[('stat_boon_small', 'Bendición Menor'), ('stat_boon_big', 'Bendición Mayor'), ('stat_curse_small', 'Maldición Menor'), ('stat_curse_big', 'Maldición Mayor'), ('gamble_spike', 'Apuesta Salvaje'), ('reroll_split', 'Reparto Caótico'), ('life_trade', 'Intercambio Vital'), ('glass_cannon', 'Cañón de Cristal'), ('turtle', 'Coraza'), ('berserk', 'Berserk'), ('bloodpact', 'Pacto de Sangre'), ('fortune_wheel', 'Rueda de la Fortuna'), ('hp_percent_shift', 'Cambio % Vida'), ('atk_percent_shift', 'Cambio % Ataque'), ('def_percent_shift', 'Cambio % Defensa')], max_length=32, null=True),
        ),
    ]
