# Generated by Django 5.2.8 on 2025-12-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0005_alter_expeditionlobby_decision_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expeditionlobby',
            name='last_effect',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
