# Generated by Django 5.2.2 on 2025-11-27 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_alter_invitationcode_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MineGameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('result', models.CharField(choices=[('retire', 'Retiro'), ('bomb', 'Bomba')], max_length=10)),
                ('finished_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mine_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-finished_at'],
            },
        ),
    ]
