# Generated by Django 5.2.2 on 2025-11-27 20:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_minegameresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='minegameresult',
            name='result',
            field=models.CharField(choices=[('retire', 'Se retiró'), ('bomb', 'Pisó bomba')], max_length=10),
        ),
        migrations.AlterField(
            model_name='minegameresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mine_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CombatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slot', models.CharField(choices=[('weapon', 'Arma'), ('helmet', 'Casco'), ('armor', 'Armadura'), ('pants', 'Pantalones'), ('boots', 'Botas'), ('shield', 'Escudo'), ('amulet', 'Amuleto')], max_length=20)),
                ('rarity', models.CharField(choices=[('basic', 'Básica'), ('uncommon', 'Poco común'), ('special', 'Especial'), ('epic', 'Épica'), ('legendary', 'Legendaria'), ('mythic', 'Mítica'), ('ascended', 'Ascendida')], max_length=20)),
                ('source', models.CharField(choices=[('shop', 'Tienda'), ('gacha', 'Gacha'), ('drop', 'Drop')], default='gacha', max_length=10)),
                ('attack', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=0)),
                ('crit_chance', models.FloatField(default=0.0)),
                ('dodge_chance', models.FloatField(default=0.0)),
                ('speed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combat_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TowerBattleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveIntegerField()),
                ('victory', models.BooleanField(default=False)),
                ('log_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tower_battles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TowerProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_floor', models.PositiveIntegerField(default=0)),
                ('max_floor_reached', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tower_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
