# Generated by Django 5.2.2 on 2025-11-27 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_userprofile_created_at_userprofile_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='towerprogress',
            name='daily_coins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='towerprogress',
            name='daily_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='equipped_amulet1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='notes.combatitem'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='equipped_amulet2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='notes.combatitem'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='equipped_amulet3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='notes.combatitem'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='equipped_armor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='notes.combatitem'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='equipped_boots',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='notes.combatitem'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='equipped_helmet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='notes.combatitem'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='equipped_pants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='notes.combatitem'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='equipped_shield',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='notes.combatitem'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='equipped_weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='notes.combatitem'),
        ),
    ]
