# Generated by Django 5.2.2 on 2025-11-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_towerprogress_daily_coins_towerprogress_daily_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GachaProbability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.CharField(choices=[('basic', 'Básica'), ('uncommon', 'Poco común'), ('special', 'Especial'), ('epic', 'Épica'), ('legendary', 'Legendaria'), ('mythic', 'Mítica'), ('ascended', 'Ascendida')], max_length=20, unique=True)),
                ('probability', models.FloatField(help_text='Probabilidad entre 0 y 1. La suma de todas las rarezas debe ser 1.0')),
            ],
            options={
                'ordering': ['rarity'],
            },
        ),
    ]
