# Generated by Django 5.2.2 on 2025-11-28 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_pvpbattlelog_pvpranking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('from_coins', models.PositiveIntegerField(default=0, help_text='Monedas que entrega el emisor.')),
                ('to_coins', models.PositiveIntegerField(default=0, help_text='Monedas que entrega el receptor.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_sent', to=settings.AUTH_USER_MODEL)),
                ('last_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades_last_actor', to=settings.AUTH_USER_MODEL)),
                ('offered_from', models.ManyToManyField(blank=True, related_name='trades_offered_from', to='notes.combatitem')),
                ('offered_to', models.ManyToManyField(blank=True, related_name='trades_offered_to', to='notes.combatitem')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
