# Generated by Django 5.2.2 on 2025-11-28 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_trade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldBossCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='Inicio local del ciclo (fase de preparación).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_damage', models.PositiveIntegerField(default=0)),
                ('turns_processed', models.PositiveIntegerField(default=0)),
                ('finished', models.BooleanField(default=False)),
                ('rewards_given', models.BooleanField(default=False)),
                ('battle_log', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-start_time'],
                'unique_together': {('start_time',)},
            },
        ),
        migrations.CreateModel(
            name='WorldBossParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_hp', models.IntegerField()),
                ('total_damage_done', models.PositiveIntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='notes.worldbosscycle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worldboss_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_damage_done', 'user__username'],
                'unique_together': {('cycle', 'user')},
            },
        ),
    ]
