# Generated by Django 5.2.2 on 2025-11-29 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_worldbosscycle_worldbossparticipant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniBossLobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss_code', models.CharField(choices=[('moth_baron', 'Varón Polilla'), ('cat_commander', 'Comandante Gato'), ('nightmare_freddy', 'Pesadilla Freddy')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('waiting', 'En espera'), ('running', 'En batalla'), ('finished', 'Finalizada')], default='waiting', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('current_turn', models.IntegerField(default=0)),
                ('total_damage', models.IntegerField(default=0)),
                ('log_text', models.TextField(blank=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miniboss_lobbies_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MiniBossParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('hp_remaining', models.IntegerField(default=0)),
                ('total_damage_done', models.IntegerField(default=0)),
                ('is_alive', models.BooleanField(default=True)),
                ('reward_coins', models.IntegerField(default=0)),
                ('reward_given', models.BooleanField(default=False)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='notes.minibosslobby')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miniboss_participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
