# Generated by Django 5.2.2 on 2025-11-29 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_minibosslobby_minibossparticipant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minibossparticipant',
            name='joined_at',
        ),
        migrations.AddField(
            model_name='minibossparticipant',
            name='boss_damage_at_death',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='minibosslobby',
            name='boss_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='minibosslobby',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miniboss_lobbies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='minibosslobby',
            name='log_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='minibosslobby',
            name='status',
            field=models.CharField(choices=[('waiting', 'En espera'), ('running', 'En batalla'), ('finished', 'Finalizado')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='minibossparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
