# Generated by Django 5.2.2 on 2025-11-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0016_remove_minibossparticipant_joined_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rubies',
            field=models.IntegerField(default=0),
        ),
    ]
