# Generated by Django 5.2.2 on 2025-11-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0017_userprofile_rubies'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auto_sell_rarities',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
