# Generated by Django 5.2.2 on 2025-12-01 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0019_marketlisting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VipShopOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('item', 'Objeto'), ('rubies', 'Paquete de rubíes')], max_length=20)),
                ('ruby_amount', models.PositiveIntegerField(default=0)),
                ('price_coins', models.PositiveIntegerField(default=0)),
                ('price_rubies', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vip_purchases', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_offers_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vip_offer', to='notes.combatitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
