# Generated by Django 5.2.2 on 2025-12-01 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0020_vipshopoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatitem',
            name='attack_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='combatitem',
            name='defense_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='combatitem',
            name='hp_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='equipped_pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='notes.combatitem'),
        ),
        migrations.AlterField(
            model_name='combatitem',
            name='slot',
            field=models.CharField(choices=[('weapon', 'Arma'), ('helmet', 'Casco'), ('armor', 'Armadura'), ('pants', 'Pantalones'), ('boots', 'Botas'), ('shield', 'Escudo'), ('amulet', 'Amuleto'), ('pet', 'Mascota')], max_length=20),
        ),
    ]
