# Generated by Django 5.2.2 on 2025-12-03 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0021_combatitem_attack_pct_combatitem_defense_pct_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Sorteo Mega MIX', max_length=100)),
                ('note', models.TextField(default='Premio: por definir.\nEl admin puede editar esta nota.')),
                ('participation_price', models.PositiveIntegerField(default=0, help_text='Precio en monedas por participar.')),
                ('status', models.CharField(choices=[('waiting', 'En espera'), ('finished', 'Finalizado')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raffles_won', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RaffleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='notes.raffle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffle_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('raffle', 'user')},
            },
        ),
    ]
