# Generated by Django 5.2.2 on 2025-12-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0022_raffle_raffleentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='accepted_by_from_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='accepted_by_to_user',
            field=models.BooleanField(default=False),
        ),
    ]
