# Generated by Django 5.2.2 on 2025-12-04 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0023_trade_accepted_by_from_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='accepted_by_from_user',
            new_name='from_confirmed',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='accepted_by_to_user',
            new_name='to_confirmed',
        ),
    ]
