# Generated by Django 5.2.2 on 2025-12-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0024_rename_accepted_by_from_user_trade_from_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gachaprobability',
            options={'ordering': ['gacha_type', 'rarity']},
        ),
        migrations.AddField(
            model_name='gachaprobability',
            name='gacha_type',
            field=models.CharField(choices=[('normal', 'Gacha normal'), ('premium', 'Gacha premium')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='gachaprobability',
            name='probability',
            field=models.FloatField(help_text='Probabilidad entre 0 y 1. La suma de todas las rarezas de ese gacha debe ser ≤ 1.0'),
        ),
        migrations.AlterField(
            model_name='gachaprobability',
            name='rarity',
            field=models.CharField(choices=[('basic', 'Básica'), ('uncommon', 'Poco común'), ('special', 'Especial'), ('epic', 'Épica'), ('legendary', 'Legendaria'), ('mythic', 'Mítica'), ('ascended', 'Ascendida')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='gachaprobability',
            unique_together={('gacha_type', 'rarity')},
        ),
    ]
